apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gitlab
  name: gitlab-cm-common
  labels:
    app: gitlab
data:
  # Timezone
  TZ: "Europe/Berlin"
  GITLAB_TIMEZONE: "Bern"
  # GitLab
  GITLAB_ROOT_EMAIL: "info@stouffcapital.com"
  GITLAB_SSH_PORT: "30022"
  GITLAB_NOTIFY_ON_BROKEN_BUILDS: "true"
  GITLAB_NOTIFY_PUSHER: "false"
  GITLAB_PIPELINE_SCHEDULE_WORKER_CRON: "*/5 * * * *"
  # GitLab Backup
  GITLAB_BACKUP_SCHEDULE: "daily"
  GITLAB_BACKUP_TIME: "04:30"
  # GitLab DB
  DB_ADAPTER: "postgresql"
  DB_TYPE: "postgres"
  DB_HOST: "gitlab-postgresql"
  DB_PORT: "5432"
  DB_USER: "gitlab"
  DB_NAME: "gitlab"
  # GitLab Redis
  REDIS_HOST: "gitlab-redis"
  REDIS_PORT: "6379"
  # Nginx settings
  #NGINX_MAX_UPLOAD_SIZE: "100m"
  # GitLab SMTP settings
  GITLAB_EMAIL: "info@stouffcapital.com"
  GITLAB_EMAIL_DISPLAY_NAME: "GitLab | StouffCapital"
  GITLAB_EMAIL_REPLY_TO: "info@stouffcapital.com"
  SMTP_ENABLED: "false"
  SMTP_DOMAIN: "example.com"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USER: "gitlab"
  SMTP_STARTTLS: "true"
  SMTP_AUTHENTICATION: "login"
  # GitLab IMAP settings
  IMAP_ENABLED: "false"
  IMAP_HOST: imap.example.com
  IMAP_PORT: "993"
  IMAP_USER: "mailer@example.com"
  IMAP_SSL: "true"
  IMAP_STARTTLS: "false"
  # docker registry
  GITLAB_REGISTRY_ENABLED: "true"
  GITLAB_REGISTRY_HOST: "registry.stouffcapital.com"
  GITLAB_REGISTRY_PORT: "443"
  GITLAB_REGISTRY_API_URL: "http://docker-registry:5000"
  GITLAB_REGISTRY_KEY_PATH: "/certs/tls.key"
  # Your other config vars below
