apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-postgresql-pv-claim
  labels:
    app: gitlab
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
